version: "3"
services:
  redis-db:
    image: redis:6.2-alpine
    container_name: "redis-db"
    restart: always
    ports:
      - '6379:6379'
    networks:
      - my_network
    volumes:
      - ./data-center/data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redisinsight:
    image: redislabs/redisinsight
    container_name: "redisinsight"
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - ./data-center/redisinsight:/db

  my-mongodb:
    image: mongo:4.2.3-bionic
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./data-center/mongodb:/data/db

  svc-publish-data:
    build:
      context: ./binanace-socket
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - "3000:3000"
    command: [ "node" , "main.js" ]

  ui-trading-board:
    build:
      context: ./trading-stock-board
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      -  ./env-config.js:/usr/share/nginx/html/env-config.js
    depends_on:
      - svc-publish-data

volumes:
  data-center:
    driver: local


networks:
  my_network:
    driver: bridge
