version: "3.8"
services:
  redis-db:
    image: redis:6.2-alpine
    container_name: "redis-db"
    restart: always
    ports:
      - '6379:6379'
    networks:
      - my_network
    volumes:
      - ./data-center/data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  svc-publish-data:
    build:
      context: ./binanace-socket
      dockerfile: Dockerfile
    networks:
      - my_network
    depends_on:
      - redis-db
    ports:
      - "3000:3000"
    environment:
      REDIS_DB_HOST: "redis-db"
      REDIS_DB_PORT: "6379"
    command: [ "node" , "main.js" ]

  ui-trading-board:
    build:
      context: ./trading-stock-board
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - svc-publish-data

  jmeter-app:
    build:
      context: ./docker-jmeter
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    depends_on:
      - svc-publish-data

volumes:
  data-center:
    driver: local


networks:
  my_network:
    driver: bridge
