version: '3'

services:
  tradingDB:
    container_name: tradingDB
    restart: unless-stopped
    image: postgres:12
    environment:
      POSTGRES_USER: trading
      POSTGRES_PASSWORD: trading
      POSTGRES_DB: trading
    volumes:
      - ./data-center/trading-data:/var/lib/postgresql/data/ #using a volume
    ports:
      - '5432:5432'
    networks:
      - trading

  adminDB:
    container_name: adminDB
    restart: unless-stopped
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./data-center/pgadmin:/var/lib/pgadmin
      - ./bk:/home/bk
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - tradingDB
    networks:
      - trading

  redisDB:
    image: redis:6.2-alpine
    container_name: "redisDB"
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./data-center/data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - trading
    depends_on:
      - tradingDB

  redisinsight:
    image: redislabs/redisinsight
    container_name: "redisinsight"
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - ./data-center/redisinsight:/db
    networks:
      - trading
    depends_on:
      - tradingDB
      - redisDB

  svc-propagator:
    build:
      context: ./service-propagator
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: tradingDB
      POSTGRES_PORT: 5432
      POSTGRES_USER: trading
      POSTGRES_PASSWORD: trading
      POSTGRES_DATABASE: trading
      REDIS_DB_HOST: redisDB
      REDIS_DB_PORT: 6379
    command: ["node" , "main.js"]
    networks:
      - trading
    depends_on:
      - tradingDB
      - redisDB


#volumes:
#  adminDB:
#  tradingDB:

networks:
  trading:
    driver: bridge

#  rSQtdidPD22gcwz
